# Generated by Django 5.0.6 on 2024-06-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True,
                help_text="Введите Дату создания продукта",
                null=True,
                verbose_name="Дата создания(записи в БД)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение продукта",
                null=True,
                upload_to="media/photo",
                verbose_name="Изображение(превью)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                help_text="Введите Дату последнего изменения продукта",
                null=True,
                verbose_name="Дата последнего изменения(записи в БД)",
            ),
        ),
    ]
