# Generated by Django 4.2.2 on 2024-07-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_edit', 'может редактировать блог')], 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
